---
name: Alicia
surname: Fennell
position: "Master's Student in Environmental Science & Management"
address: "Santa Barbara, CA"
phone: "(805) 450-5148"
email: "aliciafennell@bren.ucsb.edu"
github: aliciafennell
linkedin: alicia-fennell
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Two truths and a lie 
(placeholder - but tell me what your guess is if you read this:))


 * I've been charged by bison.
 * I've been swimming with orcas. 
 * I've been bitten by a turkey vulture.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2019-2021", "Bren School of Environmental Science & Management, University of California, Santa Barbara", "Santa Barbara, CA",
  "Bachelor of Arts", "2010-2014", "University of California, Santa Cruz", "Santa Cruz, CA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Highlighted Coursework 

```{r}
## need to get rid of the comma after data: 

tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Data:", "", "Statistics & Data Analysis for Environmental Science & Management, Advanced Data Analysis, Geographic Information Systems (GIS)", "(Bren School)",
  "Economics, Law, & Policy:", "", "Economics and Policy of Climate Change, Economics of Environmental Management, Environmental Law and Policy, Environmental Politics and Policy, Cost-Benefit Analysis and Non-market Valuation", "(Bren School)",
   "Communication:", "", "Writing Skills for Environmental Professionals, Advanced Environmental Communication, Survey Design and Environmental Public Opinion, Equity and the Environment", "(Bren School)",
  "Energy & Climate:", "", "Energy, Technology and the Environment, Climate Change Impacts and Adaptation, Earth System Science", "(Bren School)"
  
  
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Professional Experience 

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Research & Engagement Intern", "2020", "Santa Barbara County Food Action Network", "Santa Barbara, CA",
  "Teaching Assistant", "2019-2020", "University of California, Santa Barbara", "Santa Barbara, CA",
  "Environmental Educator/Naturalist", "2015-2019", "Exploring New Horizons Outdoor School", "Loma Mar, CA",
  "Summer Camp Director", "2018", "Life Lab", "Santa Cruz, CA",
  "Ecuador Trip Co-Leader", "2017", "The Road Less Traveled", "Ecuador",
  "Summer Camp Assistant Director", "2015-2016", "Life Lab", "Santa Cruz, CA",
  "Naturalist Intern", "2014-2015", "Sierra Outdoor School", "Sonora, CA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Additional Experience 

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Community Volunteer", "2017-2019", "Puente de la Costa Sur", "Pescadero, CA",
  "Conference Organizer", "2017-2019", "Pescadero Valley Conference", "Loma Mar, CA",
  "Ropes Course Facilitator", "2015-2019", "YMCA Camp Jones Gulch", "La Honda, CA"
  
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Skills and Certifications 


```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Computer & Software:", "", "Microsoft Office Suite (Excel, PowerPoint, Word), R and RStudio, ArcGIS, Slack, Zoom, Trello", "",
  "Language:", "", "Spanish (verbal and written proficiency)", "",
  "Certifications:", "", "Wilderness First Responder, California Naturalist Program (2014)", ""

) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```
